import { useEffect, useState } from 'react';
import Link from 'next/link';
import { supabase } from '../lib/supabaseClient';
import { PostList, type PostRow } from '../components/PostList';
import { useSupabaseAuth } from '../hooks/useSupabaseAuth';
import { enrichWithViewerFavorites } from '../utils/favorites';
import { enrichWithTags } from '../utils/tags';
import { validateExpression } from '../utils/expression-validator';

function shortenVersion(version: string | undefined): string | undefined {
  return version?.slice(0, 7);
}

export default function Home() {
  const { user } = useSupabaseAuth();
  const [trendingPosts, setTrendingPosts] = useState<PostRow[]>([]);
  const [trendingLoading, setTrendingLoading] = useState(true);
  const [trendingError, setTrendingError] = useState('');

  useEffect(() => {
    let cancelled = false;

    const loadTrending = async () => {
      setTrendingLoading(true);
      setTrendingError('');

      const rpcResult = await supabase.rpc('get_trending_feed', { page: 0 });

      if (cancelled) return;

      if (rpcResult.error) {
        setTrendingError(rpcResult.error.message ?? String(rpcResult.error));
        setTrendingPosts([]);
        setTrendingLoading(false);
        return;
      }

      let rows = (rpcResult.data ?? []) as PostRow[];

      if (user && rows.length > 0) {
        rows = (await enrichWithViewerFavorites((user as any).id as string, rows)) as PostRow[];
      }

      if (rows.length > 0) {
        rows = (await enrichWithTags(rows)) as PostRow[];
      }

      // Security: drop posts with invalid expressions
      rows = rows.filter((r) => validateExpression(r.expression).valid);

      setTrendingPosts(rows);
      setTrendingLoading(false);
    };

    void loadTrending();

    return () => {
      cancelled = true;
    };
  }, [user]);

  return (
    <>
      <section className="home-section">
        <h2>Welcome to BytebeatCloud!</h2>
        <p>
          A platform to <Link href="/explore">explore</Link> and <Link href="/create">share</Link>{' '}
          tiny musical expressions.
        </p>

        <p>
          This app is still in development. Expect bugs and incomplete features. Contributions
          welcome on{' '}
          <Link href="https://github.com/pckerneis/BytebeatCloud" target="_blank">
            GitHub
          </Link>
          !
        </p>

        <fieldset>
          <legend>What is bytebeat?</legend>
          <p>
            Bytebeat is a minimalist music format where sounds are generated by small programs that
            use arithmetic and bitwise operations to create unique algorithmic soundscapes.
          </p>

          <p>
            <Link href="/explore">Browse existing bytebeats</Link> or{' '}
            <Link href="/create">create your own</Link>.
          </p>
        </fieldset>

        <section style={{ marginTop: '24px' }}>
          <h3>Trending posts</h3>
          {trendingLoading && <p className="text-centered">Loading trending posts…</p>}
          {!trendingLoading && trendingError && <p className="error-message">{trendingError}</p>}
          {!trendingLoading && !trendingError && trendingPosts.length === 0 && (
            <p className="text-centered">No trending posts yet.</p>
          )}
          {!trendingLoading && !trendingError && trendingPosts.length > 0 && (
            <>
              <PostList posts={trendingPosts} currentUserId={user ? (user as any).id : undefined} />
              <p className="text-centered">
                <Link href="/explore">Explore more posts →</Link>
              </p>
            </>
          )}
        </section>

        <div className="home-footer">
          <div>
            <div>BytebeatCloud</div>
            <div title={process.env.NEXT_PUBLIC_APP_VERSION ?? 'dev'}>
              {shortenVersion(process.env.NEXT_PUBLIC_APP_VERSION) ?? 'dev'}
            </div>
          </div>
          <div>
            <div>
              <Link href="/terms">Terms of Service</Link>
            </div>
            <div>
              <Link href="/privacy">Privacy Policy</Link>
            </div>
            <div>
              <Link href="/legal-notice">Legal Notice</Link>
            </div>
          </div>
        </div>
      </section>
    </>
  );
}
