import { APP_NAME } from '../constants';
import Link from 'next/link';

export default function Home() {
  return (
    <>
      <section className="home-section">
        <h2>Welcome to {APP_NAME}!</h2>
        <p>
          A platform to <Link href="/explore">explore</Link> and <Link href="/create">share</Link>{' '}
          tiny musical expressions.
        </p>

        <fieldset>
          <legend>What is bytebeat?</legend>
          <p>
            Bytebeat is a minimalist music format where sounds are generated by small programs that
            use arithmetic and bitwise operations to create unique algorithmic soundscapes.
          </p>

          <p>
            <Link href="/explore">Browse existing bytebeats</Link> or{' '}
            <Link href="/create">create your own</Link>.
          </p>
        </fieldset>
      </section>
    </>
  );
}
