import Link from 'next/link';

export default function Home() {
  return (
    <>
      <section className="home-section">
        <h2>Welcome to BytebeatCloud!</h2>
        <p>
          A platform to <Link href="/explore">explore</Link> and <Link href="/create">share</Link>{' '}
          tiny musical expressions.
        </p>

        <p>
          This app is still in development. Expect bugs and incomplete features. Contributions
          welcome on{' '}
          <Link href="https://github.com/pckerneis/BytebeatCloud" target="_blank">
            GitHub
          </Link>
          !
        </p>

        <fieldset>
          <legend>What is bytebeat?</legend>
          <p>
            Bytebeat is a minimalist music format where sounds are generated by small programs that
            use arithmetic and bitwise operations to create unique algorithmic soundscapes.
          </p>

          <p>
            <Link href="/explore">Browse existing bytebeats</Link> or{' '}
            <Link href="/create">create your own</Link>.
          </p>
        </fieldset>

        <div className="home-footer">
          <div>BytebeatCloud</div>
          <div>v{process.env.NEXT_PUBLIC_APP_VERSION ?? 'dev'}</div>
          <div>
            <Link href="/terms">Terms of Service</Link>
          </div>
          <div>
            <Link href="/privacy">Privacy Policy</Link>
          </div>
          <div>
            <Link href="/legal-notice">Legal Notice</Link>
          </div>
        </div>
      </section>
    </>
  );
}
